# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

workflow:
  name: train-multi-gpu
  resources:
    default:  # Resources of each task
      gpu: 8
      cpu: 16
      memory: 30Gi
      storage: 30Gi
  groups:
  - name: training
    tasks:
    - name: master  # Master task for torchrun
      image: nvcr.io/nvidia/pytorch:24.03-py3
      lead: true  # Set to the lead of the group
      command: [bash]
      args: [/tmp/master.sh]
      files:
      - path: /tmp/master.sh
        contents: |
          set -ex
          mkdir -p {{output}}/models

          # Launch training
          torchrun --nnodes 2 --nproc_per_node 8 --node_rank 0 \
                    --master_addr {{host:master}} --master_port 29400 \
                    /tmp/train.py --total_epochs 10 --batch_size 32 \
                    --snapshot_path {{output}}/models/snapshot.pth
      - path: /tmp/train.py
        localpath: train.py
      outputs:
        - dataset:
            name: {{ output_dataset }}
            path: models

    - name: worker  # Worker task that will communicate with the master task
      image: nvcr.io/nvidia/pytorch:24.03-py3
      command: [bash]
      args: [/tmp/worker.sh]
      files:
      - path: /tmp/worker.sh
        contents: |
          set -ex
          mkdir -p {{output}}/models

          # Launch training
          torchrun --nnodes 2 --nproc_per_node 8 --node_rank 1 \
                    --master_addr {{host:master}} --master_port 29400 \
                    /tmp/train.py --total_epochs 10 --batch_size 32 \
                    --snapshot_path {{output}}/models/snapshot.pth
      - path: /tmp/train.py
        localpath: train.py

default-values:
  output_dataset: my-trained-model  # The name of the output dataset
