# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

workflow:
  name: train-torchrun
  resources:
    default:  # Resources of each task
      gpu: {{ n_gpus_per_node }}
      cpu: 16
      memory: 30Gi
      storage: 30Gi
  groups:
  - name: training
    tasks:
    {% for item in range(n_nodes) %}
    {% if item == 0 %}
    - name: master  # Master task for torchrun
      lead: true  # Set to the lead of the group
      outputs:  # Only save the trained model in lead task
      - dataset:
          name: {{ output_dataset }}
          path: models
    {% else %}
    - name: worker_{{item}}  # Worker task that will communicate with the master task
    {% endif %}
      image: nvcr.io/nvidia/pytorch:24.03-py3
      command: [bash]
      args: [/tmp/run.sh]
      files:
      - path: /tmp/run.sh
        contents: |
          set -ex
          mkdir -p {{output}}/models

          # Synchronize the master and all workers
          python3 /tmp/osmo_barrier.py --num_nodes {{n_nodes}} --connect {{host:master}} --rank {{item}}

          # Launch training
          torchrun --nnodes {{n_nodes}} --nproc_per_node {{n_gpus_per_node}} --node_rank {{item}} \
                    --master_addr {{host:master}} --master_port {{master_port}} \
                    /tmp/train.py --total_epochs {{n_epochs}} --batch_size {{batch_size}} \
                    --snapshot_path {{output}}/models/snapshot.pth
      - path: /tmp/train.py
        localpath: train.py
      - path: /tmp/osmo_barrier.py
        localpath: osmo_barrier.py
    {% endfor %}

default-values:
  n_gpus_per_node: 8
  n_nodes: 2  # The number of nodes to use for training, need to be greater than 1
  master_port: 29400
  n_epochs: 10
  batch_size: 32
  output_dataset: my-trained-model  # The name of the output dataset
