# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

workflow:
  name: train-single-gpu
  resources:
    default:
      gpu: 1
      cpu: 4
      memory: 10Gi
      storage: 30Gi

  tasks:
  - name: train
    image: nvcr.io/nvidia/pytorch:24.03-py3
    command: ["/bin/bash"]
    args: ["/tmp/entry.sh"]
    files:
      - path: /tmp/entry.sh
        contents: |
          set -ex

          # Directory of training inputs
          {% if input_dataset %}
          INPUT_DIR="{{input:0}}/{{input_dataset}}"
          {% else %}
          INPUT_DIR="./data"
          {% endif %}

          # Directory to store training outputs
          OUTPUT_DIR="{{output}}/experiments"
          mkdir -p $OUTPUT_DIR

          # Launch TensorBoard
          tensorboard --logdir $OUTPUT_DIR/logs &
          TENSORBOARD_PID=$!

          # Launch training
          python3 /tmp/train.py --save-model \
            --dataset-path $INPUT_DIR \
            --tensorboard-log-dir $OUTPUT_DIR/logs \
            --checkpoint-dir $OUTPUT_DIR/checkpoints \
            --model-save-path $OUTPUT_DIR/models

            # --dataset-path {{input:0}}/{{input_dataset}} \

          # Kill TensorBoard when training is done
          kill $TENSORBOARD_PID || true

      - path: /tmp/train.py
        localpath: train.py
    {% if input_dataset %}
    inputs:
      - dataset:
          name: {{ input_dataset }}
    {% endif %}
    outputs:
      - dataset:
          name: {{ output_dataset }}
          path: experiments/models  # The local path of the output dataset
    {% if checkpoint_url %}
    checkpoint:
    - path: experiments/checkpoints  # The local path of the checkpoints
      url: {{ checkpoint_url }}  # The remote path in the data store to checkpoint to
      frequency: 10s  # Time between one checkpoint ending and the next one beginning
      regex: .*.pth  # Regex for files to checkpoint
    {% endif %}

default-values:
  input_dataset: ""  # The name of the input dataset
  output_dataset: my-trained-model  # The name of the output dataset
  checkpoint_url: ""  # The remote path in the data store to checkpoint to
