# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

workflow:
  name: train-reschedule
  resources:
    default:
      gpu: {{ n_gpus_per_node }}
      cpu: 16
      memory: 30Gi
      storage: 30Gi
  groups:
  - name: training
    ignoreNonleadStatus: false
    tasks:
    {% for item in range(n_nodes) %}
    {% if item == 0 %}
    - name: master  # Master task for torchrun
      lead: true
      checkpoint:
      - path: /tmp/models
        url: {{upload_location}}
        frequency: {{checkpoint_cadence}}
    {% else %}
    - name: worker_{{item}}  # Worker task that will communicate with the master task
    {% endif %}
      image: nvcr.io/nvidia/pytorch:24.03-py3
      command: [bash]
      args: [/tmp/run.sh]
      exitActions:
        RESCHEDULE: {{ reschedule_code }}
      inputs:
      - url: {{upload_location}}/models
      files:
      - path: /tmp/run.sh
        contents: |
          set -ex

          # Copy the training checkpoint if it exists
          mkdir -p /tmp/models
          if [ -f "{{input:0}}/snapshot.pth" ]; then
              echo "Found snapshot file, copying..."
              cp {{input:0}}/snapshot.pth /tmp/models
              echo "Snapshot copied successfully"
          else
              echo "Warning: snapshot.pth not found at {{input:0}}/snapshot.pth"
          fi

          # Launch training
          torchrun --nnodes {{n_nodes}} --nproc_per_node {{n_gpus_per_node}} --node_rank {{item}} \
                    --master_addr {{host:master}} --master_port {{master_port}} \
                    /tmp/train.py --total_epochs {{n_epochs}} --batch_size {{batch_size}} \
                    --snapshot_path /tmp/models/snapshot.pth \
                    --error_log /tmp/training_errors.log

          # Check if any error happens that requires rescheduling the task
          if ls /tmp/training_errors.log.* 1> /dev/null 2>&1; then
              echo "Error: Training error log files found at /tmp/training_errors.log.*"
              echo "Exiting with code {{ reschedule_code }} and rescheduling the task"
              exit {{ reschedule_code }}
          fi

      - path: /tmp/train.py
        localpath: train.py
    {% endfor %}

default-values:
  n_gpus_per_node: 8
  n_nodes: 2
  master_port: 29400
  n_epochs: 200
  batch_size: 32
  checkpoint_cadence: 1m
  upload_location: s3://my_bucket/path
  reschedule_code: 3
